<!--
  MATSim wire-format enum-type schema for vehicle definitions (vehicleDefinitionsEnumTypes).

  THIRD-PARTY SPECIFICATION MATERIAL; NOT re-licensed as Apache-2.0.
  Adapted from the published MATSim schema:
      https://matsim.org/files/dtd/vehicleDefinitionsEnumTypes.xsd
  Upstream: MATSim (matsim.org / github.com/matsim-org/matsim).
  Original editor, as credited in the published schema:
      Dominik Grether, VSP, Berlin Institute of Technology.
  This individual specification file carries no in-file license, and its upstream
  license has not been independently verified; do not treat it as Apache-2.0 (or as
  any other license).
  Redistributed for offline interoperability validation only. See
  THIRD_PARTY_NOTICES.md in the repository root.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.matsim.org/files/dtd"
xmlns="http://www.matsim.org/files/dtd" elementFormDefault="qualified"
xmlns:xml="http://www.w3.org/XML/1998/namespace"
xml:lang="en">

<xs:simpleType name="fuelTypeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="diesel" />
    <xs:enumeration value="gasoline" />
    <xs:enumeration value="electricity" />
    <xs:enumeration value="biodiesel" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="doorOperationModeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="serial"/>
    <xs:enumeration value="parallel"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>
